### ISSUE TITLE
Why the facets button size is too big to see?

### ISSUE THREAD

**Issue by gclsoft** [PAIR-code/facets#214]
![image](https://user-images.githubusercontent.com/1269898/80313808-f5f41800-881f-11ea-82e5-91258afe3889.png)

**Comment by jameswex** [comment]
Wow that doesn't look right. Thanks for reporting. Does this always happen to you, or only in certain browsers/configurations? Have you tried it in colab instead of jupyter and does it also happen for you there?

**Comment by t-Asai** [comment]
@jameswex 
I have the same issue.
```
chrome: 81.0.4044.129
```

When I run `display(HTML(html))` for the first time it works well,
but when I re-run `display(HTML(diveHtml))` css are collapsed.
When I reload the notebook it works well, but re-run also work not well.
And When I Clear Output & save & reload & run, it works well.

This is a network log when it works well.
![スクリーンショット 2020-05-03 15 07 10](https://user-images.githubusercontent.com/33107932/80907220-18ba8b00-8d50-11ea-98bd-b4796b6c3a66.png)

And this is a network log when it doesn't works well.
![スクリーンショット 2020-05-03 15 07 29](https://user-images.githubusercontent.com/33107932/80907221-1c4e1200-8d50-11ea-82b9-f9b051204d1a.png)

It seems to have some trouble in 
```html
<link rel="import" href="hoge/facets-jupyter.html" >
```

**Comment by tszumowski** [comment]
I'm also seeing the same exact thing. Tried with jupyter notebook and jupyter lab. I came to here to report this only to see someone else has the same issue.

**Comment by jimbojw** [comment]
Thanks for these reports! I'm on it.

**Comment by jimbojw** [comment]
Should be fixed if you use the now merged [`/facets-dist/facets-jupyter.html`](https://github.com/PAIR-code/facets/blob/master/facets-dist/facets-jupyter.html).

**Comment by Benjamin-Siebold** [comment]
Unfortunately I am experiencing this issue again, along with an issue in which I display one display first, the other will not display data.
![image](https://user-images.githubusercontent.com/55265736/107803400-21e97700-6d28-11eb-9272-1aba59c9b228.png)

![image](https://user-images.githubusercontent.com/55265736/107805686-56aafd80-6d2b-11eb-8990-dcb46ba48e94.png)

python version 3.7.9 using chrome

**Comment by Italosayan** [comment]
Having same issue

**Comment by chrstfer** [comment]
Same issue still, python 3.11 on jupyter docker image 12-07-23 (Version 4.0.9)
